var FactoryConfig = {
	'E33N36': {
		need: {
			[RESOURCE_ENERGY]: 10000,
			[RESOURCE_KEANIUM]: 1000,
			[RESOURCE_KEANIUM_BAR]: 1000,
			[RESOURCE_LEMERGIUM]: 1000,
			[RESOURCE_LEMERGIUM_BAR]: 500,
			[RESOURCE_PURIFIER]: 500,
			[RESOURCE_OXIDANT]: 500,
			[RESOURCE_CONDENSATE]: 100,
			[RESOURCE_CONCENTRATE]: 300,
		},
		produceList: [RESOURCE_EXTRACT, RESOURCE_CRYSTAL],
	},
	'E35N38': {
		need: {
			[RESOURCE_ENERGY]: 10000,
			[RESOURCE_CATALYST]: 1000,
			[RESOURCE_EXTRACT]: 10,
			[RESOURCE_CONCENTRATE]: 30,
			[RESOURCE_PURIFIER]: 1000,
			[RESOURCE_REDUCTANT]: 1000,

		},
		produceList: [RESOURCE_SPIRIT, RESOURCE_PURIFIER],
	},
	'E29N34': {
		need: {
			[RESOURCE_ENERGY]: 10000,
			[RESOURCE_CONDENSATE]: 100,
			[RESOURCE_KEANIUM_BAR]: 100,
			[RESOURCE_REDUCTANT]: 100,
			[RESOURCE_ZYNTHIUM_BAR]: 100,
			[RESOURCE_UTRIUM_BAR]: 100,
		},
		produceList: [RESOURCE_CONCENTRATE, RESOURCE_COMPOSITE],
	},
	'E26N31': {
		need: {
			[RESOURCE_ENERGY]: 10000,
			[RESOURCE_KEANIUM_BAR]: 500,
			[RESOURCE_SPIRIT]: 2,
			[RESOURCE_EXTRACT]: 2,
			[RESOURCE_CONCENTRATE]: 3,
		},
		produceList: [RESOURCE_EMANATION],
	},
	'E29N33': {
		need: {
			[RESOURCE_ENERGY]: 10000,
			[RESOURCE_KEANIUM_BAR]: 500,
			[RESOURCE_CIRCUIT]: 1,
			[RESOURCE_MICROCHIP]: 3,
			[RESOURCE_EMANATION]: 1,
			[RESOURCE_SPIRIT]: 3,
			[RESOURCE_GHODIUM_MELT]: 500,
			[RESOURCE_CRYSTAL]: 500,
		},
		produceList: [RESOURCE_DEVICE, RESOURCE_ESSENCE],
	},
	'E21N32': {
		need: {
			[RESOURCE_ENERGY]: 10000,
			[RESOURCE_MIST]: 1000,
			[RESOURCE_OXYGEN]: 1000,
			[RESOURCE_HYDROGEN]: 1000,
			[RESOURCE_ZYNTHIUM]: 1000,
			[RESOURCE_KEANIUM]: 1000,
			[RESOURCE_UTRIUM]: 1000,
			[RESOURCE_LEMERGIUM]: 1000,
			[RESOURCE_GHODIUM]: 1000,
			// 压缩矿
			[RESOURCE_KEANIUM_BAR]: 500,
		},
		produceList: [RESOURCE_CONDENSATE, RESOURCE_GHODIUM_MELT, RESOURCE_LEMERGIUM_BAR, RESOURCE_UTRIUM_BAR, RESOURCE_ZYNTHIUM_BAR, RESOURCE_KEANIUM_BAR, RESOURCE_OXIDANT, RESOURCE_REDUCTANT],
	},
};

module.exports = FactoryConfig;