var FactoryConfig = {
	'E33N36': {
		need: {
			[RESOURCE_ENERGY]: 10000,
			[RESOURCE_KEANIUM]: 1000,
			[RESOURCE_KEANIUM_BAR]: 1000,
			[RESOURCE_ZYNTHIUM]: 1000,
			[RESOURCE_MIST]: 1000,
			[RESOURCE_LEMERGIUM]: 1000,
			[RESOURCE_LEMERGIUM_BAR]: 500,
			[RESOURCE_PURIFIER]: 500,
			[RESOURCE_OXIDANT]: 500,
			[RESOURCE_CONDENSATE]: 100,
			[RESOURCE_CONCENTRATE]: 300,
		},
		produceList: [RESOURCE_EXTRACT, RESOURCE_CRYSTAL, RESOURCE_CONDENSATE, RESOURCE_LEMERGIUM_BAR, RESOURCE_KEANIUM_BAR, RESOURCE_ZYNTHIUM_BAR],
	},
	'E35N38': {
		need: {
			[RESOURCE_ENERGY]: 10000,
			[RESOURCE_CATALYST]: 1000,
			[RESOURCE_KEANIUM]: 1000,
		},
		produceList: [RESOURCE_PURIFIER, RESOURCE_KEANIUM_BAR],
	},
	'E29N34': {
		need: {
			[RESOURCE_ENERGY]: 10000,
			[RESOURCE_OXYGEN]: 1000,
			[RESOURCE_HYDROGEN]: 1000,
			[RESOURCE_CONDENSATE]: 100,
			[RESOURCE_KEANIUM_BAR]: 100,
			[RESOURCE_REDUCTANT]: 100,
			[RESOURCE_ZYNTHIUM_BAR]: 100,
			[RESOURCE_UTRIUM]: 1000,
			[RESOURCE_UTRIUM_BAR]: 100,
		},
		produceList: [RESOURCE_CONCENTRATE, RESOURCE_COMPOSITE, RESOURCE_REDUCTANT, RESOURCE_UTRIUM_BAR, RESOURCE_OXIDANT],
	},
};

module.exports = FactoryConfig;